run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  govet:
    enable:
      - shadow
  revive:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  depguard:
    rules:
      main:
        deny:
          - pkg: github.com/sirupsen/logrus
            desc: "logging is allowed only by logutils.Log"
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/Vedant9500/WTF
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - hugeParam
      - rangeValCopy
  funlen:
    lines: 100
    statements: 50
  gosec:
    # Security-focused configuration
    severity: medium
    confidence: medium
    excludes:
      - G404  # Use of weak random number generator (math/rand instead of crypto/rand)
      - G306  # Poor file permissions used when writing to a file
    config:
      G101: # Look for hardcoded credentials
        pattern: "(?i)passwd|pass|password|pwd|secret|token|key"
        ignore_entropy: false
        entropy_threshold: "80.0"
        per_char_threshold: "3.0"
        truncate: "32"
      G102: # Bind to all interfaces
        bind_to_all_interfaces: true
      G103: # Audit the use of unsafe block
        audit_unsafe: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec          # Security-focused linter
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - revive
    - exportloopref  # Detects pointers to enclosing loop variables
    - noctx          # Finds sending http request without context.Context
    - sqlclosecheck  # Checks that sql.Rows and sql.Stmt are closed

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - goconst
        - gocyclo
        - gosec

    - linters:
        - gocritic
      text: "unnecessaryDefer:"
    
    - path: internal/
      linters:
        - depguard
      text: "is not allowed from list 'Main'"
    
    - path: internal/cli/
      linters:
        - gochecknoinits
