run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  govet:
    enable:
      - shadow
  revive:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  depguard:
    rules:
      main:
        deny:
          - pkg: github.com/sirupsen/logrus
            desc: "logging is allowed only by logutils.Log"
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/Vedant9500/WTF
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - hugeParam
      - rangeValCopy
  funlen:
    lines: 100
    statements: 50
  gosec:
    excludes:
      - G404
      - G306

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - revive

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - goconst
        - gocyclo
        - gosec

    - linters:
        - gocritic
      text: "unnecessaryDefer:"
    
    - path: internal/
      linters:
        - depguard
      text: "is not allowed from list 'Main'"
    
    - path: internal/cli/
      linters:
        - gochecknoinits
